module SageTokens
  COLORS = [
    "charcoal", "grey", "orange", "primary", "purple", "red", "sage", "yellow"
  ]

  COLOR_SLIDERS = [
    "charcoal", "grey", "orange", "primary", "purple", "red", "sage", "yellow",
    "charcoal-100", "grey-100", "orange-100", "primary-100", "purple-100", "red-100", "sage-100", "yellow-100",
    "charcoal-200", "grey-200", "orange-200", "primary-200", "purple-200", "red-200", "sage-200", "yellow-200",
    "charcoal-300", "grey-300", "orange-300", "primary-300", "purple-300", "red-300", "sage-300", "yellow-300",
    "charcoal-400", "grey-400", "orange-400", "primary-400", "purple-400", "red-400", "sage-400", "yellow-400",
    "charcoal-500", "grey-500", "orange-500", "primary-500", "purple-500", "red-500", "sage-500", "yellow-500"
  ]

  CONTAINER_SIZES = ["modal", "modal-lg", "xs", "sm", "md", "lg", "fluid"]

  GRID_TEMPLATES = [
    "m", "o", "ot", "om", "oo",
    "et", "em", "eo", "it", "im", "io", "se", "sm", "so",
    "te", "ti", "ts", "me", "mi", "ms", "oe", "oi", "os",
    "ete", "eti", "ets", "eme", "emi", "ems", "eoe", "eoi", "eos",
    "ite", "iti", "its", "ime", "imi", "ims", "ioe", "ioi", "ios",
    "ste", "sti", "sts", "sme", "smi", "sms", "soe", "soi", "sos",
  ]

  ICONS = [
    "add",
    "add-circle",
    "add-image",
    "add-small",
    "align-center",
    "align-justify",
    "align-left",
    "align-right",
    "arrow-corner",
    "arrow-down",
    "arrow-left",
    "arrow-right",
    "arrow-up",
    "assessment",
    "attach",
    "automations",
    "ban",
    "bold",
    "broadcast",
    "calendar-date",
    "calendar-schedule",
    "calendar-simple",
    "caret-down",
    "caret-left",
    "caret-right",
    "caret-up",
    "cart",
    "chart",
    "check",
    "check-circle",
    "circle-1",
    "circle-2",
    "circle-3",
    "circle-4",
    "circle-5",
    "circle-6",
    "circle-7",
    "circle-8",
    "circle-9",
    "clock",
    "closed-captions",
    "code",
    "color",
    "comment",
    "connect",
    "conversation",
    "copy",
    "coupon",
    "custom-field",
    "customize",
    "danger",
    "delete-circle",
    "delete-key",
    "delete-x",
    "dot-menu-horizontal",
    "down-small",
    "download",
    "draft",
    "drop",
    "duplicate",
    "email-activity",
    "enlarge",
    "enlarge-vertical",
    "favorite",
    "file",
    "filters",
    "flag",
    "folder",
    "folder-group",
    "form",
    "fullscreen",
    "funnel",
    "gear",
    "handle",
    "hashtag",
    "help",
    "horizontal-line",
    "image",
    "info-circle",
    "italic",
    "lab",
    "launch",
    "left-small",
    "list-bullet",
    "list-details",
    "list-numbers",
    "list-stack",
    "location",
    "lock",
    "loop",
    "mail",
    "mapped",
    "margin-left",
    "margin-right",
    "megaphone",
    "menu",
    "menu-alt",
    "microphone",
    "microphone-off",
    "monitor",
    "pen",
    "play",
    "play-outline",
    "preview-off",
    "preview-on",
    "product",
    "question-circle",
    "quote",
    "redo",
    "refresh",
    "remove",
    "remove-circle",
    "rename",
    "restore",
    "right-small",
    "round-dollar",
    "screen-share-off",
    "screen-share-on",
    "search",
    "search-small",
    "send-message",
    "skipped",
    "stack",
    "star",
    "stop",
    "strikethrough",
    "subscript",
    "superscript",
    "super-admin",
    "success",
    "tag",
    "theme-store",
    "trash",
    "underline",
    "undo",
    "unmapped",
    "up-small",
    "upload",
    "url",
    "user",
    "user-circle",
    "user-star",
    "users",
    "video-off",
    "video-on",
    "warning",
  ]

  ICON_SIZES = ["xs", "sm", "md", "lg", "xl", "2xl", "3xl", "4xl"]

  SPACER_SIZES = [:xs, :sm, :md, :lg, :xl, "2xs", "xs", "sm", "md", "lg", "xl", "2xl", "stage", "panel", "card", "stack"]

  STATUSES = ["danger", "draft", "info", "locked", "published", "warning"]
end
