#
# Sage Dictionary tokens
#
# Note: The contents of this file are generated by Style Dictionary
# and should not be modified directly here.
# See `/style-dictionary` directory for tokens and configurations.
#

module SageDictionary

  def SageDictionary.theme
    SageComponent.is_sage_theme_next? ? SageDictionaryNext : SageDictionaryLegacy
  end
  
  # SAGE_THEME_SWITCH
  THEME = SageDictionaryNext
  # TODO: THEME how to load correct theme dictionary here?
  # THEME = SageDictionary.theme
end
