#
# Sage Component Schemas
#
# Note: The contents of this file are generated by Style Dictionary
# and should not be modified directly here.
# See `/style-dictionary` directory for tokens and configurations.
#

module SageConfigs

  TBD = ''



  #
  # Alert
  #
  module Alert
    TOKENS = {
      color: {
        INFO: "info",
        SUCCESS: "success",
        WARNING: "warning",
        DANGER: "danger",
        PUBLISHED: "published",
      },
    }

    DEFAULTS = {
      actions: nil,
      color: "info",
      description: nil,
      dismissable: false,
      icon: nil,
      raised: false,
      title: nil,
    }

    SCHEMA = {
      actions: [
        :optional,
        String,
      ],
      color: [
        :optional,
        Set.new(TOKENS[:color].values),
      ],
      description: [
        :optional,
        String,
      ],
      dismissable: [
        :optional,
        TrueClass,
      ],
      icon: [
        :optional,
        String,
      ],
      raised: [
        :optional,
        TrueClass,
      ],
      title: [
        :optional,
        String,
      ],
    }

    SECTIONS = %w(alert_actions )
  end
end
