// Keep in sync with `packages/sage-assets/lib/stylesheets/tokens/_breakpoints.scss`
export const SAGE_RESPONSIVE_RANGES = {
  DEFAULT: 'default',
  XS: 'xs',
  XS_ONLY: 'xs_only',
  XS_TO_SM: 'xs_to_sm',
  XS_TO_MD: 'xs_to_md',
  XS_TO_LG: 'xs_to_lg',
  XS_TO_XL: 'xs_to_xl',
  XS_TO_XXL: 'xs_to_xxl',
  BEFORE_SM: 'before_sm',
  SM: 'sm',
  SM_ONLY: 'sm_only',
  SM_TO_MD: 'sm_to_md',
  SM_TO_LG: 'sm_to_lg',
  SM_TO_XL: 'sm_to_xl',
  SM_TO_XXL: 'sm_to_xxl',
  BEFORE_MD: 'before_md',
  MD: 'md',
  MD_ONLY: 'md_only',
  MD_TO_LG: 'md_to_lg',
  MD_TO_XL: 'md_to_xl',
  MD_TO_XXL: 'md_to_xxl',
  BEFORE_LG: 'before_lg',
  LG: 'lg',
  LG_ONLY: 'lg_only',
  LG_TO_XL: 'lg_to_xl',
  LG_TO_XXL: 'lg_to_xxl',
  BEFORE_XL: 'before_xl',
  XL: 'xl',
  XL_ONLY: 'xl_only',
  XL_TO_XXL: 'xl_to_xxl',
  BEFORE_XXL: 'before_xxl',
  XXL: 'xxl',
  XXL_ONLY: 'xxl_only',
};
