module ComponentsHelper
  ########################################################
  # STATUS KEY
  # Done : done
  # In Progress : doing
  # To-do : todo
  # Not applicable : no
  # Deprecated : stop
  ########################################################

  # Lists out all the available sage components
  def sage_components
    [
      # Sage Generated Components

      {
        title: "alert",
        description: "Alerts are used to indicate user-driven notifications.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "todo",
        a11y: "todo",
        react_component_slug: "sage-alert--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D351%253A5688",
      },
      {
        title: "avatar",
        description: "The Avatar component shows a user's profile image in a circular frame and allows for a few helpful modifications for different uses.",
        scss: "done",
        docs: "done",
        rails: "no",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-avatar--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D351%253A5689",
      },
      {
        title: "badge",
        description: "",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D488%253A43472",
      },
      {
        title: "banner",
        description: "A banner that displays at the top of the page, used for systemwide notifications and events.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "doing",
        a11y: "done",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D351%253A5691",
      },
      {
        title: "breadcrumbs",
        description: "Breadcrumbs provide a sense of where we are in the site structure with hyperlinks to previous areas in that structure. Our component also provides a specific \"Back link\" variation",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-breadcrumbs--single-item",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D351%253A5692",
      },
      {
        title: "button",
        description: "Standard button styling with multiple display options. Can be applied on both button and link components.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-button--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D3%253A15",
      },
      {
        title: "card",
        description: "A versatile smaller container for grouping content within panels",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "doing",
        a11y: "done",
        react_component_slug: "sage-card--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D488%253A43469",
      },
      {
        title: "form_checkbox",
        description: "Checkboxes provide users with selectable options like toggling a single setting or selecting multiple options from a list.",
        scss: "done",
        docs: "todo",
        rails: "no",
        react: "no",
        a11y: "done",
        react_component_slug: "sage-checkbox--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D488%253A43466",
      },
      {
        title: "description",
        description: "A description is composed of title and data content and is structured as a definition list.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "todo",
        a11y: "doing",
        react_component_slug: "sage-description--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D2643%253A23062",
      },
      {
        title: "container",
        description: "For setting contents of varying complexity inside a fixed space.",
        scss: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-grid--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D3106%253A25640",
      },
      {
        title: "copy_text",
        description: "A small set of components to use in places where \"copy\" text is provided such as in a Copy Button or a block of text to be copied elsewhere.",
        scss: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-copytext--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F9Km09NjlZHYWsMP7EGT8tI%2FSage-3-for-Admin%3Fnode-id%3D4195%253A20283",
      },
      {
        title: "dot",
        description: "Dots provide a subtle color cue to place beside text or other elements.",
        scss: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-dot--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D2697%253A22773",
      },
      {
        title: "empty_state",
        description: "The Empty State is displayed for main application features that have never been interacted with before. The Empty State is also used for smaller features in the app that primarily focus on data entry and have no data to show.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-emptystate--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D2470%253A23629",
      },
      {
        title: "form_input",
        description: "Basic text input form fields with 'floating' labels",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "no",
        a11y: "done",
        react_component_slug: "sage-input--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D430%253A3529",
      },
      {
        title: "form_select",
        description: "The form select presents a selectable menu of options. The options within the menu are represented by <option> elements.",
        scss: "done",
        docs: "todo",
        rails: "done",
        react: "todo",
        a11y: "done",
        react_component_slug: "sage-select--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F9Km09NjlZHYWsMP7EGT8tI%2F%255BWIP%255D-Sage-3-%25E2%2580%2594-Admin-Components%3Fnode-id%3D6999%253A21850",
      },
      {
        title: "form_textarea",
        description: "Basic text area input field with 'floating' label",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "no",
        a11y: "done",
        react_component_slug: "sage-textarea--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D3509%253A22970",
      },
      {
        title: "hint",
        description: "A hint is used to display non-critical informative text.",
        scss: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-hint--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F9Km09NjlZHYWsMP7EGT8tI%2F%255BWIP%255D-Sage-3-%25E2%2580%2594-Admin-Components%3Fnode-id%3D6999%253A23073",
      },
      {
        title: "icon",
        description: "The Icon component displays a standalone icon with customizable options. Our library of icons is available under the #{link_to("Foundation's Icons page", pages_design_path(:icon))}.".html_safe,
        scss: "todo",
        rails: "todo",
        react: "todo",
        a11y: "done",
        react_component_slug: "sage-icon--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D3%253A7",
      },
      {
        title: "link",
        description: "Links take users to another place, and usually appear within or directly following a sentence.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-link--primary",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D4137%253A21653",
      },
      {
        title: "list",
        description: "Set up neatly-formatted lists of content in bordered rows with some additional optional decorations.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-list--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D2697%253A23265",
      },
      {
        title: "lists",
        description: "Sage lists provide a few styling alternatives for unstyled and inline formatting.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        figma_embed: "",
      },
      {
        title: "loader",
        description: "Stylized loading animations for use with components",
        scss: "done",
        docs: "done",
        rails: "yes",
        react: "yes",
        a11y: "done",
        react_component_slug: "sage-loader--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D2738%253A23248",
      },
      {
        title: "media_tile",
        description: "Easily display a tile or set of tiles that showcase products, templates, or other media-based content. Referenced as 'Media Card' in Figma.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-media-tile--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F9Km09NjlZHYWsMP7EGT8tI%2F%255BWIP%255D-Sage-3-%25E2%2580%2594-Admin-Components%3Fnode-id%3D6999%253A21709",
      },
      {
        title: "progress_bar",
        description: "Displays progress with a value",
        scss: "done",
        docs: "todo",
        rails: "done",
        react: "todo",
        a11y: "done",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D737%253A22323",
      },
      {
        title: "property",
        description: "Displays a metadata item for a resource.",
        scss: "done",
        docs: "todo",
        rails: "done",
        react: "todo",
        a11y: "done",
        react_component_slug: "sage-property--primary",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D4581%253A21313",
      },
      {
        title: "radio",
        description: "Radio components provide users a way to select only one option from a list of two or more options.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "no",
        a11y: "done",
        react_component_slug: "sage-radio--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D488%253A43467",
      },
      {
        title: "search",
        description: "A self-contained search form that can be used in isolation and inside of menus.",
        scss: "doing",
        docs: "doing",
        rails: "todo",
        react: "todo",
        a11y: "done",
        react_component_slug: "sage-search--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D3516%253A22970",
      },
      {
        title: "switch",
        description: "Checkbox or radio component styled to appear as a toggle",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "no",
        a11y: "done",
        react_component_slug: "sage-switch--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D488%253A43468",
      },
      {
        title: "tab",
        description: "A tab button to be used inside a tabs component",
        scss: "done",
        docs: "done",
        rails: "doing",
        react: "todo",
        a11y: "todo",
        react_component_slug: "sage-tabs--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F9Km09NjlZHYWsMP7EGT8tI%2F%255BWIP%255D-Sage-3-%25E2%2580%2594-Admin-Components%3Fnode-id%3D6999%253A22291",
      },
      {
        title: "table",
        description: "Basic table component",
        scss: "doing",
        docs: "doing",
        rails: "done",
        react: "todo",
        a11y: "done",
        react_component_slug: "sage-table--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D2708%253A24009",
      },
      {
        title: "toast",
        description: "Displays a temporary notification to a user.",
        scss: "done",
        docs: "no",
        rails: "todo",
        react: "todo",
        a11y: "done",
        react_component_slug: "sage-toast--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D2755%253A23113",
      },
      {
        title: "toolbar",
        description: "Toolbars can include many variations for buttons, menus, and text inputs.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "done",
        a11y: "todo",
        react_component_slug: "sage-toolbar--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D3661%253A24050",
      },
      {
        title: "tooltip",
        description: "Tooltips display helpful text when users hover over an element.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "todo",
        a11y: "todo",
        react_component_slug: "sage-tooltip--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D737%253A22321",
      },
      {
        title: "dropdown",
        description: "Sage dropdown",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "todo",
        a11y: "todo",
        react_component_slug: "sage-dropdown--default",
        figma_embed: "https://www.figma.com/file/sMbtLUHSt2vfKgKjyQ3052/Sage?node-id=460%3A11339",
      },
      {
        title: "hero",
        description: "A Hero can be used to call attention to new features or content. The Hero is flexible in size and can contain text, illustrations, full bleed images, and a full bleed video thumbnail.",
        scss: "done",
        docs: "todo",
        rails: "done",
        react: "todo",
        a11y: "done",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D3686%253A21923",
      },
      {
        title: "modal",
        description: "Sage modal",
        scss: "done",
        docs: "done",
        rails: "doing",
        react: "todo",
        a11y: "todo",
        react_component_slug: "sage-modal--wired",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D2537%253A20081",
      },
      {
        title: "page_heading",
        description: "Page headings are used at the top of pages and contain the title of the page along with optional breadcrumbs, help link, action buttons, toolbar, and intro text.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "done",
        a11y: "doing",
        react_component_slug: "sage-pageheading--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D2537%253A20765",
      },
      {
        title: "pagination",
        description: "Pagination is used for splitting up results into several pages and provides controls for navigating to the next or previous page.",
        scss: "done",
        docs: "done",
        rails: "todo",
        react: "todo",
        a11y: "todo",
        react_component_slug: "sage-pagination--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D737%253A22322",
      },
      {
        title: "popover",
        description: "Popovers open upon click to show information regarding the section. It has a header/subject, minimal information, and a link to learn more",
        scss: "done",
        docs: "todo",
        rails: "done",
        react: "todo",
        a11y: "done",
        react_component_slug: "sage-popover--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D3686%253A23677",
      },
      {
        title: "sidebar",
        description: "The sidebar component is a fixed, vertical panel that typica11y displays navigation and/or page hierarchy.",
        scss: "done",
        docs: "done",
        rails: "done",
        react: "no",
        a11y: "done",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D393%253A7088",
      },
      {
        title: "tabs",
        description: "Tabs organize related content across screens, data sets, and can be used for navigation to related destinations.",
        scss: "todo",
        docs: "todo",
        rails: "todo",
        react: "todo",
        a11y: "done",
        react_component_slug: "sage-tabs--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D488%253A43471",
      },
      {
        title: "tag",
        description: "Tags show concise metadata in a compact format.",
        scss: "done",
        rails: "done",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-tag--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D835%253A21982",
      },
      {
        title: "upload_card",
        description: "The Upload Card provides a visually pleasing lockup for a file upload field along with other helpful controls.",
        scss: "done",
        docs: "done",
        rails: "todo",
        react: "done",
        a11y: "done",
        react_component_slug: "sage-uploadcard--default",
        figma_embed: "https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsMbtLUHSt2vfKgKjyQ3052%2FSage%3Fnode-id%3D2868%253A22244",
      },
    ]
  end

  # Sorts available components based on alphabet
  def sorted_sage_components
    sage_components.sort_by { |h| h[:title] }
  end

  # Archive of deprecated components
  def sage_deprecated_components
    [
      {
        title: "link_button",
        description: "",
        scss: "stop",
        docs: "stop",
        rails: "no",
        react: "stop",
        a11y: "no"
      },
      {
        title: "live_stream_wrapper",
        description: "A simple wrapper component for the Live stream application",
        scss: "stop",
        docs: "stop",
        rails: "no",
        react: "stop",
        a11y: "no"
      },
      {
        title: "null_view",
        description: "DEPRECATED: See Empty State.",
        scss: "stop",
        rails: "stop",
        react: "stop",
        a11y: "stop",
      },
    ]
  end

  # Sorts deprecated components based on alphabet
  def sorted_sage_deprecated_components
    sage_deprecated_components.sort_by { |h| h[:title] }
  end

  # Full list of active and deprecated components
  def sage_all_components
    sage_components | sage_deprecated_components
  end

  # Sorts full list of active and deprecated components based on alphabet
  def sorted_sage_all_components
    sage_all_components.sort_by { |h| h[:title] }
  end

end
