import { CLASSNAMES_SPACERS } from './spacers';
import {
  CLASSNAMES_TYPE,
  CLASSNAME_TYPE_BLOCK,
  CLASSNAMES_TYPE_COLORS,
  CLASSNAME_TRUNCATE_TEXT,
  CLASSNAME_STRIKETHROUGH,
} from './type';
import {
  CLASSNAMES_GRID_TEMPLATES,
  lookupGridTemplateClassname
} from './grid-templates';
import {
  CLASSNAMES_LINK,
} from './links';

export const SageClassnames = {
  SPACERS: { ...CLASSNAMES_SPACERS },
  TYPE: { ...CLASSNAMES_TYPE },
  TYPE_BLOCK: CLASSNAME_TYPE_BLOCK,
  TYPE_COLORS: { ...CLASSNAMES_TYPE_COLORS },
  TYPE_STRIKETHROUGH: CLASSNAME_STRIKETHROUGH,
  TRUNCATE_TEXT: CLASSNAME_TRUNCATE_TEXT,
  GRID_TEMPLATES: { ...CLASSNAMES_GRID_TEMPLATES },
  LINK: { ...CLASSNAMES_LINK },
  lookupGridTemplate: lookupGridTemplateClassname,
};
