export const TOKENS_ICONS = {
  ADD: 'add',
  ADD_CIRCLE: 'add-circle',
  ADD_IMAGE: 'add-image',
  ADD_SMALL: 'add-small',
  ALIGN_CENTER: 'align-center',
  ALIGN_JUSTIFY: 'align-justify',
  ALIGN_LEFT: 'align-left',
  ALIGN_RIGHT: 'align-right',
  ARCHIVE: 'archive',
  ARROW_CORNER: 'arrow-corner',
  ARROW_DOWN: 'arrow-down',
  ARROW_LEFT: 'arrow-left',
  ARROW_RIGHT: 'arrow-right',
  ARROW_UP: 'arrow-up',
  ASSESSMENT: 'assessment',
  AT_SIGN: 'at-sign',
  ATTACH: 'attach',
  AUTOMATIONS: 'automations',
  BAN: 'ban',
  BELL: 'bell',
  BLOG: 'blog',
  BOLD: 'bold',
  BROADCAST: 'broadcast',
  CALENDAR_DATE: 'calendar-date',
  CALENDAR_SCHEDULE: 'calendar-schedule',
  CALENDAR_SIMPLE: 'calendar-simple',
  CARD_UPDATE: 'card-update',
  CARET_DOWN: 'caret-down',
  CARET_LEFT: 'caret-left',
  CARET_RIGHT: 'caret-right',
  CARET_UP: 'caret-up',
  CART: 'cart',
  CART_ADD: 'cart-add',
  CHART: 'chart',
  CHART_FILLED: 'chart-filled',
  CHECK: 'check',
  CHECK_CIRCLE: 'check-circle',
  CHECK_CIRCLE_FILLED: 'check-circle-filled',
  CIRCLE_1: 'circle-1',
  CIRCLE_2: 'circle-2',
  CIRCLE_3: 'circle-3',
  CIRCLE_4: 'circle-4',
  CIRCLE_5: 'circle-5',
  CIRCLE_6: 'circle-6',
  CIRCLE_7: 'circle-7',
  CIRCLE_8: 'circle-8',
  CIRCLE_9: 'circle-9',
  CLOCK: 'clock',
  CLOSED_CAPTIONS: 'closed-captions',
  CODE: 'code',
  COLOR: 'color',
  COMMENT: 'comment',
  CONNECT: 'connect',
  CONVERSATION: 'conversation',
  CONTACT: 'contact',
  COLUMNS: 'columns',
  COPY: 'copy',
  COUPON: 'coupon',
  COURSE: 'course',
  CREDIT_CARD: 'credit-card',
  CUSTOM_FIELD: 'custom-field',
  CUSTOMIZE: 'customize',
  DANGER: 'danger',
  DELETE_CIRCLE: 'delete-circle',
  DELETE_KEY: 'delete-key',
  DELETE_X: 'delete-x',
  DOT_MENU_HORIZONTAL: 'dot-menu-horizontal',
  DOWN_SMALL: 'down-small',
  DOWNLOAD: 'download',
  DOWNSELL: 'downsell',
  DRAFT: 'draft',
  DROP: 'drop',
  DUPLICATE: 'duplicate',
  EMAIL_ACTIVITY: 'email-activity',
  ENLARGE: 'enlarge',
  ENLARGE_VERTICAL: 'enlarge-vertical',
  EXPAND: 'expand',
  FAVORITE: 'favorite',
  FILE: 'file',
  FILE_MONEY: 'file-money',
  FILTERS: 'filters',
  FLAG: 'flag',
  FOLDER: 'folder',
  FOLDER_GROUP: 'folder-group',
  FORM: 'form',
  FORM_FIELD: 'form-field',
  FULLSCREEN: 'fullscreen',
  FUNNEL: 'funnel',
  GEAR: 'gear',
  GEAR_FILLED: 'gear-filled',
  GRAPH: 'graph',
  GRANT_OFFER: 'grant-offer',
  HANDLE: 'handle',
  HANDLE_2: 'handle-2',
  HANDLE_2_VERTICAL: 'handle-2-vertical',
  HASHTAG: 'hashtag',
  HEADING_LARGE: 'heading-large',
  HEADING_SMALL: 'heading-small',
  HELP: 'help',
  HELP_FILLED: 'help-filled',
  HOME: 'home',
  HOME_ALT: 'home-alt',
  HOME_FILLED: 'home-filled',
  HORIZONTAL_LINE: 'horizontal-line',
  IMAGE: 'image',
  INFO_CIRCLE: 'info-circle',
  ITALIC: 'italic',
  KAJABI: 'kajabi',
  LAB: 'lab',
  LAUNCH: 'launch',
  LEFT_SMALL: 'left-small',
  LIST_BULLET: 'list-bullet',
  LIST_DETAILS: 'list-details',
  LIST_NUMBERS: 'list-numbers',
  LIST_STACK: 'list-stack',
  LOCATION: 'location',
  LOCK: 'lock',
  LOCK_ALT: 'lock-alt',
  LOOP: 'loop',
  MAIL: 'mail',
  MAPPED: 'mapped',
  MARGIN_LEFT: 'margin-left',
  MARGIN_RIGHT: 'margin-right',
  MEGAPHONE: 'megaphone',
  MEGAPHONE_FILLED: 'megaphone-filled',
  MENU: 'menu',
  MENU_ALT: 'menu-alt',
  MENU_BORDERED: 'menu-bordered',
  MERGE: 'merge',
  MICROPHONE: 'microphone',
  MICROPHONE_OFF: 'microphone-off',
  MONITOR: 'monitor',
  MONITOR_FILLED: 'monitor-filled',
  NEWSLETTER: 'newsletter',
  ONE_OFF_SESSION: 'one-off-session',
  PACKAGE: 'package',
  PEN: 'pen',
  PHONE_TOOLBAR: 'phone-toolbar',
  PLAY: 'play',
  PLAY_OUTLINE: 'play-outline',
  PLUG: 'plug',
  PREVIEW_OFF: 'preview-off',
  PREVIEW_ON: 'preview-on',
  PRODUCT: 'product',
  PRODUCT_FILLED: 'product-filled',
  QUESTION_CIRCLE: 'question-circle',
  QUOTE: 'quote',
  REDO: 'redo',
  REFRESH: 'refresh',
  REMOVE: 'remove',
  REMOVE_CIRCLE: 'remove-circle',
  RENAME: 'rename',
  RESET_PASSWORD: 'reset-password',
  RESTORE: 'restore',
  RIGHT_SMALL: 'right-small',
  ROUND_DOLLAR: 'round-dollar',
  SCREEN_SHARE_OFF: 'screen-share-off',
  SCREEN_SHARE_ON: 'screen-share-on',
  SEARCH: 'search',
  SEARCH_SMALL: 'search-small',
  SELECT: 'select',
  SEND_MESSAGE: 'send-message',
  SEQUENCES: 'sequences',
  SKIPPED: 'skipped',
  SPEAKER: 'speaker',
  STACK: 'stack',
  STAR: 'star',
  STOP: 'stop',
  STRIKETHROUGH: 'strikethrough',
  SUBSCRIPT: 'subscript',
  SUCCESS: 'success',
  SUPERSCRIPT: 'superscript',
  SUPER_ADMIN: 'super-admin',
  SYNC: 'sync',
  TAG: 'tag',
  TAG_FILLED: 'tag-filled',
  THEME_STORE: 'theme-store',
  TRASH: 'trash',
  UNDERLINE: 'underline',
  UNDO: 'undo',
  UNMAPPED: 'unmapped',
  UP_SMALL: 'up-small',
  UPLOAD: 'upload',
  URL: 'url',
  USER: 'user',
  USER_CIRCLE: 'user-circle',
  USER_CIRCLE_FILLED: 'user-circle-filled',
  USER_STAR: 'user-star',
  USER_STAR_FILLED: 'user-star-filled',
  USERS: 'users',
  USERS_ALT: 'users-alt',
  VIDEO_OFF: 'video-off',
  VIDEO_ON: 'video-on',
  WARNING: 'warning',
  WINDOW_PARAGRAPH: 'window-paragraph',
  WORLD: 'world'
};

export type TokensIcons =
  | 'add'
  | 'add-circle'
  | 'add-image'
  | 'add-small'
  | 'align-center'
  | 'align-justify'
  | 'align-left'
  | 'align-right'
  | 'archive'
  | 'arrow-corner'
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up'
  | 'assessment'
  | 'at-sign'
  | 'attach'
  | 'automations'
  | 'ban'
  | 'bell'
  | 'blog'
  | 'bold'
  | 'broadcast'
  | 'calendar-date'
  | 'calendar-schedule'
  | 'calendar-simple'
  | 'card-update'
  | 'caret-down'
  | 'caret-left'
  | 'caret-right'
  | 'caret-up'
  | 'cart'
  | 'chart'
  | 'check'
  | 'check-circle'
  | 'check-circle-filled'
  | 'circle-1'
  | 'circle-2'
  | 'circle-3'
  | 'circle-4'
  | 'circle-5'
  | 'circle-6'
  | 'circle-7'
  | 'circle-8'
  | 'circle-9'
  | 'clock'
  | 'closed-captions'
  | 'code'
  | 'color'
  | 'comment'
  | 'connect'
  | 'conversation'
  | 'copy'
  | 'coupon'
  | 'credit-card'
  | 'custom-field'
  | 'customize'
  | 'danger'
  | 'delete-circle'
  | 'delete-key'
  | 'delete-x'
  | 'dot-menu-horizontal'
  | 'down-small'
  | 'download'
  | 'draft'
  | 'drop'
  | 'duplicate'
  | 'email-activity'
  | 'enlarge'
  | 'enlarge-vertical'
  | 'favorite'
  | 'file'
  | 'file-money'
  | 'filters'
  | 'flag'
  | 'folder'
  | 'folder-group'
  | 'form'
  | 'fullscreen'
  | 'funnel'
  | 'gear'
  | 'graph'
  | 'handle'
  | 'hashtag'
  | 'help'
  | 'home'
  | 'home-alt'
  | 'horizontal-line'
  | 'image'
  | 'info-circle'
  | 'italic'
  | 'kajabi'
  | 'lab'
  | 'launch'
  | 'left-small'
  | 'list-bullet'
  | 'list-details'
  | 'list-numbers'
  | 'list-stack'
  | 'location'
  | 'lock'
  | 'lock-alt'
  | 'loop'
  | 'mail'
  | 'mapped'
  | 'margin-left'
  | 'margin-right'
  | 'megaphone'
  | 'menu'
  | 'menu-alt'
  | 'menu-bordered'
  | 'merge'
  | 'microphone'
  | 'microphone-off'
  | 'monitor'
  | 'newsletter'
  | 'one-off-session'
  | 'package'
  | 'pen'
  | 'phone-toolbar'
  | 'play'
  | 'play-outline'
  | 'plug'
  | 'preview-off'
  | 'preview-on'
  | 'product'
  | 'question-circle'
  | 'quote'
  | 'redo'
  | 'refresh'
  | 'remove'
  | 'remove-circle'
  | 'rename'
  | 'restore'
  | 'right-small'
  | 'round-dollar'
  | 'screen-share-off'
  | 'screen-share-on'
  | 'search'
  | 'search-small'
  | 'select'
  | 'send-message'
  | 'sequences'
  | 'skipped'
  | 'speaker'
  | 'stack'
  | 'star'
  | 'stop'
  | 'strikethrough'
  | 'subscript'
  | 'success'
  | 'superscript'
  | 'super-admin'
  | 'sync'
  | 'tag'
  | 'theme-store'
  | 'trash'
  | 'underline'
  | 'undo'
  | 'unmapped'
  | 'up-small'
  | 'upload'
  | 'url'
  | 'user'
  | 'user-circle'
  | 'user-star'
  | 'users'
  | 'users-alt'
  | 'video-off'
  | 'video-on'
  | 'warning'
  | 'window-paragraph'
  | 'world'
