import { TOKENS_COLORS, TOKENS_COLOR_PALETTE, TOKENS_COLOR_SLIDERS } from './colors';
import { TOKENS_BOX_SHADOW_OPTIONS } from './box_shadows';
import { TOKENS_GRID_GAP_OPTIONS } from './grid_gap_options';
import { TOKENS_GRID_TEMPLATES } from './grid-templates';
import { TOKENS_ICONS } from './icons';
import { TOKENS_RECHARTS } from './recharts';
import { TOKENS_SPACERS } from './spacers';
import { TOKENS_Z_INDEXES } from './z-indexes';
import { SAGE_BREAKPOINT_QUERIES, SAGE_BREAKPOINT_VALUES } from './breakpoints';

export const SageTokens = {
  BREAKPOINTS: SAGE_BREAKPOINT_VALUES,
  BREAKPOINT_QUERIES: SAGE_BREAKPOINT_QUERIES,
  BOX_SHADOWS: TOKENS_BOX_SHADOW_OPTIONS,
  COLORS: TOKENS_COLORS,
  COLOR_PALETTE: TOKENS_COLOR_PALETTE,
  COLOR_SLIDERS: TOKENS_COLOR_SLIDERS,
  GRID_GAP_OPTIONS: TOKENS_GRID_GAP_OPTIONS,
  GRID_TEMPLATES: TOKENS_GRID_TEMPLATES,
  ICONS: TOKENS_ICONS,
  RECHARTS: TOKENS_RECHARTS,
  SPACERS: TOKENS_SPACERS,
  Z_INDEXES: TOKENS_Z_INDEXES,
};
