FROM circleci/ruby:2.4.9-node-browsers AS base

USER root

RUN apt-get update -qq\
  && apt-get install -y vim\
  && rm -rf /var/lib/apt/lists/*

COPY ./docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]

WORKDIR /app/docs

COPY Gemfile /app/docs/Gemfile
COPY lib/sage_rails /app/docs/lib/sage_rails

RUN gem install bundler -v 1.17.3
RUN bundle install

EXPOSE 4000
EXPOSE 4035
