# frozen_string_literal: true

source 'https://rubygems.org'

ruby "2.7.7"

gem 'rails', '6.0.6'

gem 'sass-rails', '~> 6.0'
gem 'uglifier', '>= 1.3.0'
gem 'webpacker', '~> 4.3', '>= 4.3.0'

gem 'sage_rails', path: 'lib/sage_rails'
gem "kaminari", "~> 1.2.1"

group :production do
  gem 'rails_12factor'
end

group :development, :test do
  gem 'byebug'
  gem 'pry'
  gem "rspec-rails", ">= 4.0.1"
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 3.7', '>= 3.7.0'

  # Spring speeds up development by keeping your application running in the
  # background. Read more: https://github.com/rails/spring
  gem "spring", "~> 2.1.1"

  # CLI Version Bumping Utility
  #  Used by bin/sage-tag.sh to automate sage_rails version bump workflow
  gem "bump", "~> 0.9.0"

  gem "listen", "~> 3.5.1"
end

gem "lockup", "~> 1.5", ">= 1.5.1"
gem "redcarpet"
gem "rouge"
