# frozen_string_literal: true

source 'https://rubygems.org'

ruby "3.3.9"

gem 'rails', '~> 7.2.0'

gem 'sprockets-rails'
gem 'sass-rails', '~> 6.0'
gem 'uglifier', '>= 1.3.0'
gem 'shakapacker', '~> 7.2'

gem 'sage_rails', path: 'lib/sage_rails'
gem "kaminari", "~> 1.2"

group :development, :test do
  gem 'byebug'
  gem 'pry'
  gem "rspec-rails", "~> 7.1"
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 4.2'

  # Spring speeds up development by keeping your application running in the
  # background. Read more: https://github.com/rails/spring
  gem "spring", "~> 4.2"

  # CLI Version Bumping Utility
  #  Used by bin/sage-tag.sh to automate sage_rails version bump workflow
  gem "bump", "~> 0.9.0"

  gem "listen", "~> 3.9"
end

gem "redcarpet"
gem "rouge"
