//
// Sage Component Schemas
//
// Note: The contents of this file are generated by Style Dictionary
// and should not be modified directly here.
// See `/style-dictionary` directory for tokens and configurations.
//


//
// Alert
//

const Alert_color_token = {
  'INFO': 'info',
  'SUCCESS': 'success',
  'WARNING': 'warning',
  'DANGER': 'danger',
  'PUBLISHED': 'published',
};

export const Alert = {
  tokens: {
    color: Alert_color_token,
  },
  defaults: {
    actions: null,
    color: 'info',
    description: null,
    dismissable: false,
    icon: null,
    raised: false,
    title: null,
  },
  schema: {
    actions: PropTypes.node,
    color: PropTypes.oneOf(Object.values(Alert_color_token)),
    description: PropTypes.string,
    dismissable: PropTypes.bool,
    icon: PropTypes.string,
    raised: PropTypes.bool,
    title: PropTypes.string,
  },
};
