//
// Sage Component Schemas
//
// Note: The contents of this file are generated by Style Dictionary
// and should not be modified directly here.
// See `/style-dictionary` directory for tokens and configurations.
//


//
// Alert
//

export const ALERT_COLOR_OPTIONS = {
  INFO: 'info',
  SUCCESS: 'success',
  WARNING: 'warning',
  DANGER: 'danger',
  PUBLISHED: 'published',
};

export const Alert = {
  tokens: {
    color: ALERT_COLOR_OPTIONS,
  },
  defaults: {
    actions: null,
    color: 'info',
    description: null,
    dismissable: false,
    icon: null,
    raised: false,
    title: null,
  },
  schema: {
    actions: PropTypes.node,
    color: PropTypes.oneOf(Object.values(ALERT_COLOR_OPTIONS)),
    description: PropTypes.string,
    dismissable: PropTypes.bool,
    icon: PropTypes.string,
    raised: PropTypes.bool,
    title: PropTypes.string,
  },
};
