name: "GetDX Service Identification"

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
      - 'develop'

jobs:
  identify-services:
    runs-on: ubuntu-latest
    steps:
      - name: Identify Services
        uses: Kajabi/getdx-monorepo-service-identifier-action@main
        with:
          getdx-instance-name: 'kajabi'
          getdx-token: ${{ secrets.GETDX_DEPLOYMENT_TOKEN }}