name: Lint-Test-Build
on:
  workflow_dispatch:
  pull_request:
jobs:
  lint_test_build:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJSON(vars.NODE_VERSIONS) }}
    steps:
      - name: Clone Sage-Lib Repo
        uses: actions/checkout@v3

      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: npm install -g yarn

      - name: Yarn Install
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: yarn install

      - name: Yarn Lint
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: yarn lint

      - name: Yarn Test
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: yarn test

      - name: Yarn Build
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: yarn build
