name: Lint-Test-Build
on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  lint_test_build:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJSON(vars.NODE_VERSIONS) }}
    steps:
      - name: Clone Sage-Lib Repo
        uses: actions/checkout@v4

      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # # Setup Auth token to push to github packages
      - name: Set NPM Config
        run: npm config set '//npm.pkg.github.com/:_authToken=${{ secrets.ACCESS_TOKEN }}'

      - name: Install Yarn
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          if (( $NODE_VERSION >= 18 )); then
            NODE_OPTIONS=--openssl-legacy-provider npm install -g yarn
          else
            npm install -g yarn
          fi

      - name: Yarn Install
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          if (( $NODE_VERSION >= 18 )); then
            NODE_OPTIONS=--openssl-legacy-provider yarn install
          else
            yarn install
          fi


      - name: Yarn Lint
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          if (( $NODE_VERSION >= 18 )); then
            NODE_OPTIONS=--openssl-legacy-provider yarn lint
          else
            yarn lint
          fi

      - name: Yarn Test
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          if (( $NODE_VERSION >= 18 )); then
            NODE_OPTIONS=--openssl-legacy-provider yarn test
          else
            yarn test
          fi

      - name: Yarn Build
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          if (( $NODE_VERSION >= 18 )); then
            NODE_OPTIONS=--openssl-legacy-provider yarn build
          else
            yarn build
          fi
