name: Lint-Test-Build
on:
  workflow_dispatch:
  pull_request:
jobs:
  lint_test_build:
    name: Lint, Test, Build
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.5
    with:
      node-version: "14.19.3"
      yarn-version: "1.22.5"
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
      parallel-commands-on-agents: |
        npx lerna run lint
        npx lerna run test
        npx lerna run build

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.5
    with:
      number-of-agents: 3
