name: Lint-Test-Build
on:
  workflow_dispatch:
  pull_request:
jobs:
  lint_test_build:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJSON(vars.NODE_VERSIONS) }}
    steps:
      - name: Clone Sage-Lib Repo
        uses: actions/checkout@v3

      - name: Set Node Version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          if [[ $NODE_VERSION == '18' ]]; then
            NODE_OPTIONS=--openssl-legacy-provider npm install -g yarn
          else
            npm install -g yarn
          fi

      - name: Yarn Install
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          if [[ $NODE_VERSION == '18' ]]; then
            NODE_OPTIONS=--openssl-legacy-provider yarn install
          else
            yarn install
          fi


      - name: Yarn Lint
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          if [[ $NODE_VERSION == '18' ]]; then
            NODE_OPTIONS=--openssl-legacy-provider yarn lint
          else
            yarn lint
          fi

      - name: Yarn Test
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          if [[ $NODE_VERSION == '18' ]]; then
            NODE_OPTIONS=--openssl-legacy-provider yarn test
          else
            yarn test
          fi

      - name: Yarn Build
        env:
          NODE_VERSION: ${{ matrix.node-version }}
        run: |
          if [[ $NODE_VERSION == '18' ]]; then
            NODE_OPTIONS=--openssl-legacy-provider yarn build
          else
            yarn build
          fi
