name: Tag Release Image
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: SHA of commit to deploy
        required: true
      environment:
        description: Optional environment to specify release for
        required: false
        default: development
jobs:
  tag_release_image:
    name: Tag and push Sage images for release
    runs-on: ubuntu-latest
    steps:
      - name: Determine release tag suffix
        uses: haya14busa/action-cond@v1
        id: release_tag_suffix
        with:
          cond: ${{ github.event.inputs.environment == 'production' }}
          if_true: 'release'
          if_false: 'release-${{ github.event.inputs.environment }}'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.SAGE_ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SAGE_ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: SageECRPushSession

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.9.1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Retag Documentation image on ECR
        uses: akhilerm/tag-push-action@v2.0.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_SAGE_DOCS }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
          RELEASE_TAG: ${{ github.event.inputs.image_tag }}-${{ steps.release_tag_suffix.outputs.value }}
        with:
          src: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_SAGE_DOCS }}:${{ env.IMAGE_TAG }}
          dst: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_SAGE_DOCS }}:${{ env.RELEASE_TAG }}
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_SAGE_DOCS }}:${{ steps.release_tag_suffix.outputs.value }}

      - name: Retag Sassdocs image on ECR
        uses: akhilerm/tag-push-action@v2.0.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_SAGE_SASSDOCS }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
          RELEASE_TAG: ${{ github.event.inputs.image_tag }}-${{ steps.release_tag_suffix.outputs.value }}
        with:
          src: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_SAGE_SASSDOCS }}:${{ env.IMAGE_TAG }}
          dst: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_SAGE_SASSDOCS }}:${{ env.RELEASE_TAG }}
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_SAGE_SASSDOCS }}:${{ steps.release_tag_suffix.outputs.value }}

      - name: Retag Storybook image on ECR
        uses: akhilerm/tag-push-action@v2.0.0
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_SAGE_STORYBOOK }}
          IMAGE_TAG: ${{ github.event.inputs.image_tag }}
          RELEASE_TAG: ${{ github.event.inputs.image_tag }}-${{ steps.release_tag_suffix.outputs.value }}
        with:
          src: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_SAGE_STORYBOOK }}:${{ env.IMAGE_TAG }}
          dst: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_SAGE_STORYBOOK }}:${{ env.RELEASE_TAG }}
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_SAGE_STORYBOOK }}:${{ steps.release_tag_suffix.outputs.value }}
      # - name: Success Datadog event
      #   if: success()
      #   uses: masci/datadog@v1
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      #     RELEASE_TAG: ${{ github.event.inputs.image_tag }}-${{ steps.release_tag_suffix.outputs.value }}
      #     RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #   with:
      #     api-key: ${{ secrets.DATADOG_API_KEY }}
      #     events: |
      #       - title: "deployment.github_action.tag-release-image"
      #         text: "%%%\n[GitHub Action Run](${{ env.RUN_URL }})\n%%%"
      #         alert_type: "success"
      #         host: "${{ github.runner.name }}"
      #         tags:
      #           - "env:${{ github.event.inputs.environment }}"
      #           - "repository:${{ github.repository }}"
      #           - "git.commit.sha:${{ github.event.inputs.image_tag }}"
      #           - "image_name:${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}"
      #           - "image_tag:${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.RELEASE_TAG }}"
      #           - "short_image:${{ env.ECR_REPOSITORY }}"
      # - name: Failure Datadog event
      #   if: failure()
      #   uses: masci/datadog@v1
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      #     RELEASE_TAG: ${{ github.event.inputs.image_tag }}-${{ steps.release_tag_suffix.outputs.value }}
      #     RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      #   with:
      #     api-key: ${{ secrets.DATADOG_API_KEY }}
      #     events: |
      #       - title: "deployment.github_action.tag-release-image"
      #         text: "%%%\n[GitHub Action Run](${{ env.RUN_URL }})\n%%%"
      #         alert_type: "error"
      #         host: "${{ github.runner.name }}"
      #         tags:
      #           - "env:${{ github.event.inputs.environment }}"
      #           - "repository:${{ github.repository }}"
      #           - "git.commit.sha:${{ github.event.inputs.image_tag }}"
      #           - "image_name:${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}"
      #           - "image_tag:${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.RELEASE_TAG }}"
      #           - "short_image:${{ env.ECR_REPOSITORY }}"