---
name: "Update-Release"

on:
  push:
    tags:
      - "v*"

jobs:
  update-release:
    name: "Update Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Update release based on tag"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false