---
name: "Update-Release"

on:
  push:
    tags:
      - "@kajabi/sage@*"

jobs:
  update-release:
    name: "Update Release"
    runs-on: "ubuntu-latest"

    steps:
      # Checkout the repository
      - name: "Checkout this repo to find Sage version"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: "0"

      # Find Sage version from package.json in docs/
      - name: "Find Sage version from docs -> package.json version"
        id: "extract_version"
        uses: "Saionaro/extract-package-version@v1.1.1"
        with:
          path: 'docs/'

      # Update release using name from script above
      - name: "Update Release based on Tag"
        uses: "ncipollo/release-action@v1"
        with:
          token: "${{ secrets.UPDATE_RELEASE_WORKFLOW_TOKEN }}"
          tag: "v${{ steps.extract_version.outputs.version }}"
          body: "See [changelog](https://github.com/Kajabi/sage-lib/blob/main/docs/CHANGELOG.md) for more information."

