---
name: "Update-Release"

on:
  push:
    tags:
      - "@kajabi/sage@*"

jobs:
  update-release:
    name: "Update Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Update release based on Sage tag"
      - uses: ""
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
