apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sage-react
  description: React components for the Sage ecosystem
  tags:
    - react
    - javascript
  links:
    - url: https://sage-lib-storybook.herokuapp.com/
      title: Storybook Site
      icon: dashboard
  annotations:
    circleci.com/project-slug: github/Kajabi/sage-lib
spec:
  type: library
  lifecycle: production
  owner: user-experience
  system: sage
  subcomponentOf: sage-lib
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sage-storybook-site
  description: The public-facing Storybook site for Sage
  tags:
    - react
    - javascript
    - storybook
  links:
    - url: https://sage-lib-storybook.herokuapp.com/
      title: Storybook Site
      icon: dashboard
spec:
  type: website
  lifecycle: production
  owner: user-experience
  system: sage
  subcomponentOf: sage-react
