import { TOKENS_COLORS, TOKENS_COLOR_PALETTE, TOKENS_COLOR_SLIDERS } from './colors';
import { TOKENS_GRID_GAP_OPTIONS } from './grid_gap_options';
import { TOKENS_GRID_TEMPLATES } from './grid-templates';
import { TOKENS_ICONS } from './icons';
import { TOKENS_RECHARTS } from './recharts';
import { TOKENS_SPACERS } from './spacers';
import { TOKENS_Z_INDEXES } from './z-indexes';

export const SageTokens = {
  COLORS: TOKENS_COLORS,
  COLOR_PALETTE: TOKENS_COLOR_PALETTE,
  COLOR_SLIDERS: TOKENS_COLOR_SLIDERS,
  GRID_TEMPLATES: TOKENS_GRID_TEMPLATES,
  GRID_GAP_OPTIONS: TOKENS_GRID_GAP_OPTIONS,
  ICONS: TOKENS_ICONS,
  RECHARTS: TOKENS_RECHARTS,
  SPACERS: TOKENS_SPACERS,
  Z_INDEXES: TOKENS_Z_INDEXES,
};
